### ISSUE TITLE
Get to user entity from password authentication

### ISSUE THREAD

**Issue by santiph** [API-Skeletons/zf-oauth2-doctrine#51]
On my application, I'm trying to perform a login and retrieve the user profile back from the services.

I'm authenticating the user by performing an `/oauth` POST call with the following body:

```
{
    "grant_type": "password",
    "username": "test",
    "password": "test",
    "client_id": "webappLocal"
}
```

And getting this back from the apigility server:
```
{
  "access_token": "0105d6385de255969d00b3a69af47687e9b8dff9",
  "expires_in": 3600,
  "token_type": "Bearer",
  "scope": "",
  "refresh_token": "666f1ecc0e7f4e52dcd2c3daa5273684ad6c24c6"
}
```

I have a `/user` endpoint where I could get the user information for a giver user_id, but I'm missing such Id. At this point, I'm only aware of the access_token, username and password of the user.

What's the best way to solve this? Can I modify the authentication response to include a user_id? Should I perform a user search by username (maybe `/user?username=test`)? I'd appreciate some direction...

**Comment by viniciusgava** [comment]
Hello, I have something like this in my application. I create a rpc service named "me" that return the information of the authenticated user.

````php
$valid = $this->validateOAuth2('me');
        if ($valid instanceof ApiProblem) {
            return new ApiProblemResponse($valid);
        }

        $e = $this->getEvent();
        $identity = $e->getParam('ZF\MvcAuth\Identity');
        if ($identity instanceof \ZF\MvcAuth\Identity\AuthenticatedIdentity) {
            try {
                $user = $this->userRepository->findByAuthenticatedIdentity($identity);
                $userInfo = $user->getArrayCopy();
                unset($userInfo['password']);
                return new JsonModel($userInfo);
            } catch(\Exception $e) {
                return new ApiProblemResponse(
                    new ApiProblem($e->getCode(), $e->getMessage())
                );
            }
        }
        $response = $this->getResponse();
        $response->setStatusCode(401);
        return $response;
````

For my case this solution is better because I do not need seek details about others users, just the authenticated. If one day I need to seek details about others users, I will do another service like you cited.
