### ISSUE TITLE
Conflict between zf-oauth2-doctrine and doctrine-module

### ISSUE THREAD

**Issue by hagzzz** [API-Skeletons/zf-oauth2-doctrine#52]
Hello,

When I activate zf-oauth2-doctrine, I can't use anymore the console command of doctrine-module package (ie. "doctrine-module migrations:diff --no-interaction")

The problem is :
PHP Notice:  Undefined index: zf-oauth2-doctrine in /var/www/vendor/api-skeletons/zf-oauth2-doctrine/Module.php on line 49
and then :
PHP Catchable fatal error:  Argument 1 passed to Zend\Config\Config::__construct() must be of the type array, null given, called in /var/www/vendor/api-skeletons/zf-oauth2-doctrine/Module.php on line 49 and defined in /var/www/vendor/zendframework/zend-config/src/Config.php on line 57

Can you help me to solve this or find a workaround ?

**Comment by TomHAnderson** [comment]
You didn't copy https://github.com/API-Skeletons/zf-oauth2-doctrine/blob/master/config/oauth2.doctrine-orm.global.php.dist to your autoload directory else the array wouldn't be null.
