### ISSUE TITLE
DoctrineModule 0.10.0 support

### ISSUE THREAD

**Issue by varuna82** [API-Skeletons/zf-oauth2-doctrine#56]
Is there a problem with updating dependency of the doctrine/doctrine-module to 0.10.0? Dependency for the doctrine/doctrine-module is set to ^0.9 currently.

**Comment by TomHAnderson** [comment]
doctrine-module is now at 1.0.0 but there is a problem with zend-hydrator:
https://github.com/doctrine/DoctrineModule/pull/548

When this module is fixed zf-apigility-doctrine and this module will be updated to use doctrine-module 2.0

**Comment by varuna82** [comment]
Thanks for the reply. I'll wait for the update. Keep up the good work as always.

**Comment by TomHAnderson** [comment]
Fixed with https://github.com/API-Skeletons/zf-oauth2-doctrine/commit/fa40539f5a25f3c82b1a397f47bbdc61319c00d6
