### ISSUE TITLE
doctrine-module dependency is forced to 0.8.* version

### ISSUE THREAD

**Issue by thomasvargiu** [API-Skeletons/zf-oauth2-doctrine#57]
Setting `doctrine-module` requiring version `^0.8`, as it's a pre-1.0 release, means `>=0.8.0 <0.9.0`.
There is a problem with 0.9.*? Or just a mistake?

**Comment by TomHAnderson** [comment]
The problem is DoctrineModule does not support ZF2 > 2.4.  I've been trying to get this corrected for over a month.  Comments on this thread are appreciated:

https://github.com/doctrine/DoctrineModule/issues/546

**Comment by TomHAnderson** [comment]
Correction; the ZF2 > 2.4 issue is not at issue here.

**Comment by TomHAnderson** [comment]
Fixed with https://github.com/API-Skeletons/zf-oauth2-doctrine/commit/fa40539f5a25f3c82b1a397f47bbdc61319c00d6

**Comment by thomasvargiu** [comment]
Should be better to use `~0.8 || ^1.0`

**Comment by thomasvargiu** [comment]
@TomHAnderson is it really resolved? Is it possible to tag the master?
