### ISSUE TITLE
Error 500 /aouth request bearer grant password

### ISSUE THREAD

**Issue by mpozzo** [API-Skeletons/zf-oauth2-doctrine#58]
if i update my composer , the request return status 500 internal error

Unable to istanziate Service Manager

I started from a clean project 

there is my composer log:

Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing zendframework/zendxml (1.0.0)
  - Installing zendframework/zendxml (1.0.2)
    Loading from cache

  - Removing zendframework/zend-stdlib (2.5.1)
  - Installing zendframework/zend-stdlib (2.7.6)
    Loading from cache

  - Installing zendframework/zend-hydrator (1.1.0)
    Loading from cache

  - Removing zendframework/zend-eventmanager (2.5.1)
  - Installing zendframework/zend-eventmanager (2.6.3)
    Loading from cache

  - Removing zendframework/zend-code (2.5.1)
  - Installing zendframework/zend-code (2.6.2)
    Loading from cache

  - Removing zendframework/zend-server (2.5.1)
  - Installing zendframework/zend-server (2.6.1)
    Loading from cache

  - Removing zendframework/zend-math (2.5.1)
  - Installing zendframework/zend-math (2.6.0)
    Loading from cache

  - Installing container-interop/container-interop (1.1.0)
    Loading from cache

  - Removing zendframework/zend-validator (2.5.1)
  - Installing zendframework/zend-validator (2.6.0)
    Loading from cache

  - Removing zendframework/zend-uri (2.5.1)
  - Installing zendframework/zend-uri (2.5.2)
    Loading from cache

  - Removing zendframework/zend-http (2.5.1)
  - Installing zendframework/zend-http (2.5.4)
    Loading from cache

  - Removing zendframework/zend-view (2.5.1)
  - Installing zendframework/zend-view (2.6.4)
    Loading from cache

  - Removing zendframework/zend-json (2.5.1)
  - Installing zendframework/zend-json (2.6.1)
    Loading from cache

  - Removing zendframework/zend-servicemanager (2.5.1)
  - Installing zendframework/zend-servicemanager (2.7.5)
    Loading from cache

  - Removing zendframework/zend-text (2.5.1)
  - Installing zendframework/zend-text (2.6.0)
    Loading from cache

  - Removing zendframework/zend-filter (2.5.1)
  - Installing zendframework/zend-filter (2.6.1)
    Loading from cache

  - Removing zendframework/zend-inputfilter (2.5.1)
  - Installing zendframework/zend-inputfilter (2.6.0)
    Loading from cache

  - Removing zendframework/zend-form (2.5.1)
  - Installing zendframework/zend-form (2.7.0)
    Loading from cache

  - Installing psr/http-message (1.0)
    Loading from cache

  - Installing zendframework/zend-diactoros (1.3.3)
    Loading from cache

  - Installing zendframework/zend-psr7bridge (0.2.1)
    Loading from cache

  - Removing zendframework/zend-mvc (2.5.1)
  - Installing zendframework/zend-mvc (2.7.1)
    Loading from cache

  - Removing zendframework/zend-dom (2.5.1)
  - Installing zendframework/zend-dom (2.6.0)
    Loading from cache

  - Removing zendframework/zend-console (2.5.1)
  - Installing zendframework/zend-console (2.6.0)
    Loading from cache

  - Removing symfony/yaml (v2.7.0)
  - Installing symfony/yaml (v3.0.3)
    Loading from cache

  - Removing sebastian/version (1.0.5)
  - Installing sebastian/version (1.0.6)
    Loading from cache

  - Removing sebastian/global-state (1.0.0)
  - Installing sebastian/global-state (1.1.1)
    Loading from cache

  - Removing sebastian/recursion-context (1.0.0)
  - Installing sebastian/recursion-context (1.0.2)
    Loading from cache

  - Removing sebastian/exporter (1.2.0)
  - Installing sebastian/exporter (1.2.1)
    Loading from cache

  - Removing sebastian/environment (1.2.2)
  - Installing sebastian/environment (1.3.5)
    Loading from cache

  - Removing sebastian/diff (1.3.0)
  - Installing sebastian/diff (1.4.1)
    Loading from cache

  - Removing sebastian/comparator (1.1.1)
  - Installing sebastian/comparator (1.2.0)
    Loading from cache

  - Removing phpunit/php-text-template (1.2.0)
  - Installing phpunit/php-text-template (1.2.1)
    Loading from cache

  - Removing doctrine/instantiator (1.0.4)
  - Installing doctrine/instantiator (1.0.5)
    Loading from cache

  - Removing phpunit/php-timer (1.0.5)
  - Installing phpunit/php-timer (1.0.7)
    Loading from cache

  - Removing phpunit/php-file-iterator (1.4.0)
  - Installing phpunit/php-file-iterator (1.4.1)
    Loading from cache

  - Removing phpunit/php-token-stream (1.4.1)
  - Installing phpunit/php-token-stream (1.4.8)
    Loading from cache

  - Removing phpspec/prophecy (v1.4.1)
  - Installing phpspec/prophecy (v1.6.0)
    Loading from cache

  - Removing phpunit/phpunit-mock-objects (2.3.3)
  - Installing phpunit/phpunit-mock-objects (3.0.6)
    Loading from cache

  - Installing sebastian/code-unit-reverse-lookup (1.0.0)
    Loading from cache

  - Removing phpunit/php-code-coverage (2.1.5)
  - Installing phpunit/php-code-coverage (3.2.1)
    Loading from cache

  - Installing myclabs/deep-copy (1.5.0)
    Loading from cache

  - Installing sebastian/resource-operations (1.0.0)
    Loading from cache

  - Removing phpunit/phpunit (4.7.2)
  - Installing phpunit/phpunit (5.2.9)
    Loading from cache

  - Removing zendframework/zend-test (2.5.1)
  - Installing zendframework/zend-test (2.6.1)
    Loading from cache

  - Removing zendframework/zend-tag (2.5.1)
  - Installing zendframework/zend-tag (2.6.1)
    Loading from cache

  - Removing zendframework/zend-session (2.5.1)
  - Installing zendframework/zend-session (2.6.2)
    Loading from cache

  - Removing zendframework/zend-serializer (2.5.1)
  - Installing zendframework/zend-serializer (2.6.1)
    Loading from cache

  - Removing zendframework/zend-progressbar (2.5.1)
  - Installing zendframework/zend-progressbar (2.5.2)
    Loading from cache

  - Removing zendframework/zend-permissions-acl (2.5.1)
  - Installing zendframework/zend-permissions-acl (2.6.0)
    Loading from cache

  - Removing zendframework/zend-paginator (2.5.1)
  - Installing zendframework/zend-paginator (2.6.0)
    Loading from cache

  - Removing zendframework/zend-navigation (2.5.1)
  - Installing zendframework/zend-navigation (2.6.0)
    Loading from cache

  - Removing zendframework/zend-modulemanager (2.5.1)
  - Installing zendframework/zend-modulemanager (2.7.1)
    Loading from cache

  - Removing zendframework/zend-crypt (2.5.1)
  - Installing zendframework/zend-crypt (2.6.0)
    Loading from cache

  - Removing zendframework/zend-mail (2.5.1)
  - Installing zendframework/zend-mail (2.6.1)
    Loading from cache

  - Installing psr/log (1.0.0)
    Loading from cache

  - Removing zendframework/zend-log (2.5.1)
  - Installing zendframework/zend-log (2.7.1)
    Loading from cache

  - Removing zendframework/zend-i18n-resources (2.5.1)
  - Installing zendframework/zend-i18n-resources (2.5.2)
    Loading from cache

  - Removing zendframework/zend-i18n (2.5.1)
  - Installing zendframework/zend-i18n (2.6.0)
    Loading from cache

  - Removing zendframework/zend-file (2.5.1)
  - Installing zendframework/zend-file (2.6.1)
    Loading from cache

  - Removing zendframework/zend-feed (2.5.1)
  - Installing zendframework/zend-feed (2.7.0)
    Loading from cache

  - Removing zendframework/zend-di (2.5.1)
  - Installing zendframework/zend-di (2.6.0)
    Loading from cache

  - Removing zendframework/zend-db (2.5.1)
  - Installing zendframework/zend-db (2.7.0)
    Loading from cache

  - Removing zendframework/zend-config (2.5.1)
  - Installing zendframework/zend-config (2.6.0)
    Loading from cache

  - Removing zendframework/zend-captcha (2.5.1)
  - Installing zendframework/zend-captcha (2.5.4)
    Loading from cache

  - Removing zendframework/zend-cache (2.5.1)
  - Installing zendframework/zend-cache (2.6.1)
    Loading from cache

  - Removing zendframework/zend-barcode (2.5.1)
  - Installing zendframework/zend-barcode (2.6.0)
    Loading from cache

  - Removing zendframework/zend-authentication (2.5.1)
  - Installing zendframework/zend-authentication (2.5.3)
    Loading from cache

  - Removing zendframework/zendframework (2.5.1)
  - Installing zendframework/zendframework (2.5.3)
    Loading from cache

  - Removing zfcampus/zf-hal (1.2.1)
  - Installing zfcampus/zf-hal (1.3.0)
    Loading from cache

  - Removing zfcampus/zf-apigility-admin (1.3.3)
  - Installing zfcampus/zf-apigility-admin (1.4.1)
    Loading from cache

Writing lock file
Generating autoload files

**Comment by jackdpeterson** [comment]
I can reproduce the issue simply by calling OPTIONS on /oauth

```
Additional information:

Zend\ServiceManager\Exception\ServiceNotFoundException

File:
/var/www/domains/com.example.apigility/vendor/zendframework/zend-servicemanager/src/ServiceManager.php:557
Message:
Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for ServiceManager
Stack trace:
#0 /var/www/domains/com.example.apigility/vendor/zfcampus/zf-oauth2/src/Factory/AuthControllerFactory.php(22): Zend\ServiceManager\ServiceManager->get('ServiceManager')
#1 [internal function]: ZF\OAuth2\Factory\AuthControllerFactory->createService(Object(Zend\Mvc\Controller\ControllerManager), 'zfoauth2control...', 'ZF\\OAuth2\\Contr...')
#2 /var/www/domains/com.example.apigility/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(936): call_user_func(Array, Object(Zend\Mvc\Controller\ControllerManager), 'zfoauth2control...', 'ZF\\OAuth2\\Contr...')
#3 /var/www/domains/com.example.apigility/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(330): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'zfoauth2control...', 'ZF\\OAuth2\\Contr...')
#4 /var/www/domains/com.example.apigility/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(287): Zend\ServiceManager\AbstractPluginManager->createServiceViaCallback(Array, 'zfoauth2control...', 'ZF\\OAuth2\\Contr...')
#5 /var/www/domains/com.example.apigility/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(636): Zend\ServiceManager\AbstractPluginManager->createFromFactory('zfoauth2control...', 'ZF\\OAuth2\\Contr...')
#6 /var/www/domains/com.example.apigility/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(599): Zend\ServiceManager\ServiceManager->doCreate('ZF\\OAuth2\\Contr...', 'zfoauth2control...')
#7 /var/www/domains/com.example.apigility/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(532): Zend\ServiceManager\ServiceManager->create(Array)
#8 /var/www/domains/com.example.apigility/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(161): Zend\ServiceManager\ServiceManager->get('ZF\\OAuth2\\Contr...', true)
#9 /var/www/domains/com.example.apigility/vendor/zendframework/zend-mvc/src/DispatchListener.php(94): Zend\ServiceManager\AbstractPluginManager->get('ZF\\OAuth2\\Contr...')
#10 [internal function]: Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
#11 /var/www/domains/com.example.apigility/vendor/zendframework/zend-eventmanager/src/EventManager.php(490): call_user_func(Array, Object(Zend\Mvc\MvcEvent))
#12 /var/www/domains/com.example.apigility/vendor/zendframework/zend-eventmanager/src/EventManager.php(263): Zend\EventManager\EventManager->triggerListeners('dispatch', Object(Zend\Mvc\MvcEvent), Object(Closure))
#13 /var/www/domains/com.example.apigility/vendor/zendframework/zend-mvc/src/Application.php(340): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
#14 /var/www/domains/com.example.apigility/public/index.php(61): Zend\Mvc\Application->run()
#15 {main}```

**Comment by jackdpeterson** [comment]
This is unrelated to this project and I'll submit a PR for this that resolves the issue in the appropriate repo.
