### ISSUE TITLE
Column definitions according to OAuth specifications

### ISSUE THREAD

**Issue by Wilt** [API-Skeletons/zf-oauth2-doctrine#59]
According to [bshaffer his OAuth cookbook](http://bshaffer.github.io/oauth2-server-php-docs/cookbook/) there are specific column definitions for valid OAuth database storage:

````
CREATE TABLE oauth_clients (client_id VARCHAR(80) NOT NULL, client_secret VARCHAR(80), redirect_uri VARCHAR(2000) NOT NULL, grant_types VARCHAR(80), scope VARCHAR(100), user_id VARCHAR(80), CONSTRAINT clients_client_id_pk PRIMARY KEY (client_id));
CREATE TABLE oauth_access_tokens (access_token VARCHAR(40) NOT NULL, client_id VARCHAR(80) NOT NULL, user_id VARCHAR(255), expires TIMESTAMP NOT NULL, scope VARCHAR(2000), CONSTRAINT access_token_pk PRIMARY KEY (access_token));
CREATE TABLE oauth_authorization_codes (authorization_code VARCHAR(40) NOT NULL, client_id VARCHAR(80) NOT NULL, user_id VARCHAR(255), redirect_uri VARCHAR(2000), expires TIMESTAMP NOT NULL, scope VARCHAR(2000), CONSTRAINT auth_code_pk PRIMARY KEY (authorization_code));
CREATE TABLE oauth_refresh_tokens (refresh_token VARCHAR(40) NOT NULL, client_id VARCHAR(80) NOT NULL, user_id VARCHAR(255), expires TIMESTAMP NOT NULL, scope VARCHAR(2000), CONSTRAINT refresh_token_pk PRIMARY KEY (refresh_token));
CREATE TABLE oauth_users (username VARCHAR(255) NOT NULL, password VARCHAR(2000), first_name VARCHAR(255), last_name VARCHAR(255), CONSTRAINT username_pk PRIMARY KEY (username));
CREATE TABLE oauth_scopes (scope TEXT, is_default BOOLEAN);
CREATE TABLE oauth_jwt (client_id VARCHAR(80) NOT NULL, subject VARCHAR(80), public_key VARCHAR(2000), CONSTRAINT jwt_client_id_pk PRIMARY KEY (client_id));
````

In our custom entities we added these column specifics in the entity class definitions like this:

    @ORM\Column(type="string", name="client_id", length=80, nullable=false)
    @ORM\Column(type="string", name="client_secret", length=80, nullable=true)
    @ORM\Column(type="string", name="redirect_uri", length=2000, nullable=false)
    etc etc.

I would like to use the default entities that come with the library for our application, but I cannot because these column declarations are missing.
This is needed because without these specific column definitions the columns created in the database (when automatically creating database tables from the entity definitions) will not correspond to the OAuth specs.

I can make a pull request where I add column definitions according to OAuth specs to these columns.

**Comment by TomHAnderson** [comment]
Where's the JTI?  If you don't handle JTI and you are handling JWT you're not handling the whole of OAuth2 so what your'e calling `specs` is just an implementation of the OAuth2.  The SQL definition of the implementation is not itself a `spec`.

The SQL you list is incomplete and not 3NF or BCNF.  I submit to you the schema created by the **Doctrine Adapter** is more correct.  The columns you added with underscores to delimit the column names, which breaks [canonical naming](https://docs.google.com/presentation/d/1k_2fJ1QfbQrHxws6h5bKAcQKThFjL7MgCCfSGKFQJYg/edit#slide=id.p).

I'll be giving a talk in SDPHP on the topic of canonical naming this month.
