### ISSUE TITLE
constructor dependency injection for ObjectManager

### ISSUE THREAD

**Issue by Wilt** [API-Skeletons/zf-oauth2-doctrine#66]
This is more a question @TomHAnderson or possibly a suggestion for improvement.

The `DoctrineAdapter` class is hard dependent on an `ObjectManager` instance. Why not use a constructor dependency injection pattern to set the `ObjectManager` inside the Adapter?

**Comment by TomHAnderson** [comment]
http://blog.tomhanderson.com/2016/08/initializer-pattern-or-constructor_11.html

I am very much against constructor injection.  Please read that article I wrote last week on my position and I'd love feedback so I can reinforce my view.

**Comment by Wilt** [comment]
A lot of people won't agree with you...

1) A common criticism towards this solution is that initializers are killing for performance since every class that is initialized by the `ServiceManager` will be pulled through the `initialize` method of all your different initializers.
2) I am also not sure whether constructor dependency injection _"locks down anyone who wants to use the class in another unseen way"_. Factories can be overwritten and classes can be extended, so people will be able to add their own logic and create the their custom class with their own factory and add the result to a `ServiceLocator` by simply using the same name.
3) When using an initializer solution there is  a risk (i.e. initializers are not configured correctly) that you end up with a class that is missing hard dependencies. When using a constructor dependency injection pattern this is not possible since the class cannot be instantiated without the dependencies.

Read also [here](https://github.com/zendframework/zendframework/issues/6068) for an interesting discussion on this topic

**Comment by TomHAnderson** [comment]
This post defines the issue well:  https://github.com/zendframework/zendframework/issues/6068#issuecomment-122605372

I also like the argument [simple vs enterprisey](https://github.com/zendframework/zendframework/issues/6068#issuecomment-39135241) Ocramius puts forward.  As for me I code for enterprise worthy code.

One last point re your point 1) initializers are generally used in an application as part of a plugin manager, itself a service manager, and not on the global service manager.  So for the classes in the plugin manager it will only make sense to send them all through the defined initializers.

**Comment by TomHAnderson** [comment]
More experience shows constructor injection is preferred and you can see some of that in the latest commits.

**Comment by Wilt** [comment]
:smile: Very honest of you, I think it will prove to be a good change.
