### ISSUE TITLE
client_id is not identifier column and has no unique constraint

### ISSUE THREAD

**Issue by Wilt** [API-Skeletons/zf-oauth2-doctrine#67]
In the entity model for this module the `client_id` is not an identifier column, instead a separate identifier column is used in the mapper for `Client` [here](https://github.com/API-Skeletons/zf-oauth2-doctrine/blob/master/config/orm/ZF.OAuth2.Doctrine.Entity.Client.dcm.xml#L4)

Would it not be better to simply use the `client_id` as an identifier column?
~~Since the `client_id` is not an INDEX should there not be an unique constraint added for `client_id`?~~

**EDIT**
My bad, I noticed that unique constraint is added [here](https://github.com/API-Skeletons/zf-oauth2-doctrine/blob/35561e07b30a59074740df8412be9c1b80206db3/src/EventListener/DynamicMappingSubscriber.php#L86), but the first question remains...

**Comment by TomHAnderson** [comment]
https://github.com/API-Skeletons/zf-oauth2-doctrine/blob/master/config/orm/ZF.OAuth2.Doctrine.Entity.Client.dcm.xml#L7

Are you asking about `clientId` or `client_id`?  The `clientId` field is the 'username' for the Client.  

In the entities that reference the Client entity `client_id` is used:  https://github.com/API-Skeletons/zf-oauth2-doctrine/blob/master/config/orm/ZF.OAuth2.Doctrine.Entity.PublicKey.dcm.xml#L10

**Comment by Wilt** [comment]
_Maybe my question wasn't clear... I will try once more._

In the `Client` entity there is [an identifier column ](https://github.com/API-Skeletons/zf-oauth2-doctrine/blob/master/config/orm/ZF.OAuth2.Doctrine.Entity.Client.dcm.xml#L4) and [a `clientId` column](https://github.com/API-Skeletons/zf-oauth2-doctrine/blob/master/config/orm/ZF.OAuth2.Doctrine.Entity.Client.dcm.xml#L4) (what you refer to as username for the client). Why not use the clientId column as the identifier column for your client entity? IMO an additional identifier column is not needed since the `clientId` column uniquely identifies the client (and can also be used for associations).

**Comment by TomHAnderson** [comment]
Using string identifiers is not a best practice for database applications.  The entities AccessToken, AuthorizationCode, and RefreshToken all have a foreign key to the Client entity.  In my view not using a string for a primary key is second nature.

To rephrase your question, should a User entity use the email address as the primary key?  It could be a unique field?  Now what if the user changes their email address?   

http://programmers.stackexchange.com/questions/189026/why-is-the-usage-of-string-keys-generally-considered-to-be-a-bad-idea
https://social.msdn.microsoft.com/Forums/sqlserver/en-US/fd7685b1-701e-49c8-8087-888857afb741/using-varchar-for-primary-key-value-ok?forum=transactsql

**Comment by Wilt** [comment]
Thanks for your response. I understand your reasoning, but I don't totally agree with the analogy of email address as a key for a user entity...

A rule of thumb for primary keys is that it won't change over it's lifetime. [Here on this IBM page](http://www.ibm.com/support/knowledgecenter/SSEPEK_11.0.0/apsg/src/tpc/db2z_defineparentkeyuniqueindex.html) (just a pick from google, there are many more):

> Choose a primary key whose values will not change over time. Choosing a primary key with persistent values enforces the good practice of having unique identifiers that remain the same for the lifetime of the entity occurrence.

Meaning the email address would be a bad choice for a primary key in a user table, but the client id won't change over the record's lifetime so could very well be a primary key.

Thanks for the discussion though...
