### ISSUE TITLE
Default Entities private properties

### ISSUE THREAD

**Issue by exptom** [API-Skeletons/zf-oauth2-doctrine#70]
I'd like to extend the default entities in my application. All the entity attributes are private rather than protected which prevents me from using an extended version of the entity classes.

My use case is that I need the tables to store uuid's rather than integer id's and to achieve this I need to generate the uuid within the entity constructor. e.g.:

```
namespace ZF\ApigilityDoctrine\Entity;

use Ramsey\Uuid\Uuid;
use ZF\OAuth2\Doctrine\Entity\AccessToken as ZFOAuth2_AccessToken;

class AccessToken extends ZFOAuth2_AccessToken
{

    public function __construct()
    {
        $this->id = Uuid::uuid4();
        parent::__construct();
    }
}
```

This fails as the entity attributes are not accessible due to being private. Is there a reason that they couldn't be made protected instead?

**Comment by TomHAnderson** [comment]
Changing all the entity properties to protected is unnecessary.  Because your id field is a string you're already changing the ORM metadata.  So instead of 
```xml
<id name="id" type="integer">
      <generator strategy="AUTO"/>
 </id>
```
use `strategy="UUID"`.

http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html#identifier-generation-strategies

**Comment by exptom** [comment]
I store UUIDs as a binary type="uuid_binary"  (https://github.com/ramsey/uuid-doctrine/blob/master/src/UuidBinaryType.php) so need id to be an instance of Uuid object.

**Comment by TomHAnderson** [comment]
Does that mean you've already explored the UUID strategy in Doctrine and it doesn't use the native uuid_binary field to store a UUID identifier?  I think there's more research to be done here.  

If you find the UUID strategy cannot populate a Doctrine uuid_binary column you may submit a PR but you're the first to request non-private properties.  I think a better way to solve this unique problem is to modify the config to allow for custom entities.

**Comment by exptom** [comment]
Yes, the uuid_binary column is introduced by the ramsey/uuid-doctrine module. Doctrine's internal UUID strategy does not support binary storage.

My Current workaround has been to set the config in your module to use custom entities and duplicate the majority of your entity code in my own entities but these seems a bit of an unclean way to handle it.

**Comment by TomHAnderson** [comment]
I still think the correct answer is to use Doctrine to autogenerate the UUID.

Here is where a custom strategy is applied:  https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.php#L696

And here is the current UUID strategy: 
https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Id/UuidGenerator.php

Create a new UuidBinary strategy and assign that to the metadata.

**Comment by TomHAnderson** [comment]
And, that new strategy could be PR'd into the ramsey/uuid-doctrine module....too late, it's already there: https://github.com/ramsey/uuid-doctrine/blob/master/src/UuidGenerator.php

So I think you just need to use that generator in your metadata.

**Comment by TomHAnderson** [comment]
The https://github.com/ramsey/uuid-doctrine repo describes how to use it's custom UUID generator for UUID Binary:
```php
     * @GeneratedValue(strategy="CUSTOM")
     * @CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
```

**Comment by exptom** [comment]
The disadvantage of using the generator is that you don't know the id before your ask Doctrine to persist the entity. I use the constructor to set my application entity properties so that they are in a known state as soon as they are created.

**Comment by TomHAnderson** [comment]
If you're using your id as a primary key and you're using Doctrine there's no need to know the id before you flush.  I think this discussion has turned because it's now a discussion of when a primary key should be generated and has moved away from zf-oauth2-doctrine content.  

I won't be changing the entities as you requested.  You'll need to generate your own to access properties in your way.

**Comment by exptom** [comment]
There are reasons for wanting an entity state to be correct before Doctrine flushes (Ocramius' Doctrine best practices talk covers it - https://vimeo.com/134178140).

But I agree that for this module that is not necessary (I was just following the way that entities work in the rest of our app). I will implement using the custom id generator for the oauth2 entities.

Thanks for your help and creating this awesome module :smile:
