### ISSUE TITLE
zf-oauth2-doctrine wokrs very slowly

### ISSUE THREAD

**Issue by Sohorev** [API-Skeletons/zf-oauth2-doctrine#72]
Hello, standart zf-oauth2 working for 0.3 seconds from start request to receive response
But when I am try to use zf-oauth2-doctrine it works 3.5 seconds. 
It very slowly for me
What me do?

**Comment by TomHAnderson** [comment]
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/caching.html
zf-oauth2-doctrine does not add significant time over a standard Doctrine installation.  If you are using a virtual machine be sure that's not the cause.

**Comment by Sohorev** [comment]
I am using ubuntu 14 without virtual machine
I am using redis cache for metadata, query and result

Please help me
I am create simple repository https://github.com/Sohorev/apigility-zf-oauth2-doctrine-slowly.git
with all for use it

View ./README.md file and ./config/autoload/local.php.dist for requirements
After install run migrations for create oauth2 tables

**Comment by Sohorev** [comment]
When debug code I am find slowly place: this is verifyHash with bcrypt. 
I am change bcrypt_cost from 14 to 10 and regenerate passwords
After it code works with 0.8 seconds
Thank you
