### ISSUE TITLE
HTTP Basic Auth is Broken Because of AuthenticationPostListener

### ISSUE THREAD

**Issue by hanialaraj** [API-Skeletons/zf-oauth2-doctrine#74]
If there is an http basic adapter and try to use it with an API service (given that there is an api service using oauth2_doctrine auth adapter):

Catchable fatal error:  Argument 1 passed to ZF\OAuth2\Doctrine\Identity\AuthenticationPostListener::findAccessToken() must be of the type array, string given, called in /Users/hani/Projects/MedcorTM-PHP-API/vendor/api-skeletons/zf-oauth2-doctrine-identity/src/AuthenticationPostListener.php on line 33 and defined in /Users/hani/Projects/MedcorTM-PHP-API/vendor/api-skeletons/zf-oauth2-doctrine-identity/src/AuthenticationPostListener.php on line 44

**Comment by TomHAnderson** [comment]
The problem you have is understandable because zf-oauth2-doctrine-identity was not designed to work nicely with other authentication mechanisms.  If you would like to submit a pull request to fix this issue please submit a PR to the appropriate repository.
