### ISSUE TITLE
grant_type Error 

### ISSUE THREAD

**Issue by neifar-I** [API-Skeletons/zf-oauth2-doctrine#79]
> php public/index.php

result

> ZF\OAuth2\Doctrine\Console

  index.php oauth2:client:create               Create client                                                   
  index.php oauth2:client:list                 List clients                                                    
  index.php oauth2:client:update --id=#        Update client                                                   
  index.php oauth2:client:delete --id=#        Delete client                                                   
  index.php oauth2:scope:create                Create scope                                                    
  index.php oauth2:scope:list                  List scopes                                                     
  index.php oauth2:scope:update --id=#         Update scope                                                    
  index.php oauth2:scope:delete --id=#         Delete scope                                                    
  index.php oauth2:public-key:create --id=#    Create public key.  id is a client record.                      
  index.php oauth2:public-key:delete --id=#    Delete public key.  id is a client record.                      
  index.php oauth2:jwt:create --id=#           Create a JWT entry.  id is a client record.                     
  index.php oauth2:jwt:list                    List JWT entries                                                
  index.php oauth2:jwt:delete --id=#           Delete a JWT entry.  id is a jwt record.    `

when I run 
> php public/index.php oauth2:client:create in terminal I get nothing

**Comment by TomHAnderson** [comment]
Try oauth2:client:list   If that also fails you may be using windows or a non-terminal terminal.  A posix adapter is expected: https://github.com/API-Skeletons/zf-oauth2-doctrine-console/blob/master/src/Controller/ClientController.php#L12 

p.s. this is actually a question for zf-oauth2-doctrine-console.

**Comment by neifar-I** [comment]
i use ubuntu 16.04 terminal

**Comment by TomHAnderson** [comment]
It's not ZF3 compatible, yet.  https://github.com/API-Skeletons/zf-oauth2-doctrine/blob/master/config/module.config.php#L6

The controllers expect a $this->getServiceLocator() in them.  To fix this each controller must be paired with a factory.  I look forward to the PR!

**Comment by TomHAnderson** [comment]
Closing this issue; this is not an issue with this module.  See API-Skeletons/zf-oauth2-doctrine-console

**Comment by MichaelGooden** [comment]
FYI, we use this in ZF3, albeit with deprecation notices. Still runs though.

**Comment by TomHAnderson** [comment]
This module now has an official 2.x branch for ZF3
