### ISSUE TITLE
Problem with orm:schema-tool:create

### ISSUE THREAD

**Issue by dliebel** [API-Skeletons/zf-oauth2-doctrine#83]
Hello
Excuse my english

I have a problem executing the command

`orm: schema-tool: create`

the error is as follows
![image](https://user-images.githubusercontent.com/4933136/31254564-926e70ba-a9ff-11e7-83c7-86c3c811ee3c.png)

when making a

![image](https://user-images.githubusercontent.com/4933136/31254689-221925a2-aa00-11e7-9198-3bf7ecd5c09a.png)

I was reviewing the documentation but everything is fine
I do not know if you have any suggestions ...

**Comment by sariabod** [comment]
@dliebel this may be a silly question, but did you create the User entity and reference it in the config under dynamic_mapping?

**Comment by dliebel** [comment]
@sariabod If you were right it was a silly mistake.

I had bad reference to the user entity

Thank you, sorry for the inconvenience.
