### ISSUE TITLE
Can not change field datatype

### ISSUE THREAD

**Issue by brndusic** [API-Skeletons/zf-oauth2-doctrine#84]
Tried to change field datatype in AccessToken entity and noticed that configuration for datatype is ignored.

Also how can I add additional indexes to table, is that possible?

**Comment by TomHAnderson** [comment]
Please be more specific about the AccessToken field you want to change.

As for additional indexes, yes, you can add them but you need to do it dynamically.  For instance https://github.com/API-Skeletons/zf-oauth2-doctrine/blob/master/src/EventListener/DynamicMappingSubscriber.php#L86 creates a dynamic index.

**Comment by brndusic** [comment]
Thank you @TomHAnderson 
I'm trying to change access_token field datatype on AccessToken entity and want to add index on it. I tried to accomplish that by changing zf-oauth2-doctrine configuration like:
```php
        'AccessToken' => array(
            'entity' => 'ZF\OAuth2\Doctrine\Entity\AccessToken',
            'mapping' => array(
                'access_token' => array(
                    'type' => 'field',
                    'name' => 'accessToken',
                    'datatype' => 'text',
                    // 'datatype' => 'string'  //<-- THIS LINE IS IGNORED
                ),
                'expires' => array(
                    'type' => 'field',
                    'name' => 'expires',
                    'datatype' => 'datetime'
                ),
                'scope' => array(
                    'type' => 'collection',
                    'name' => 'scope',
                    'entity' => 'ZF\OAuth2\Doctrine\Entity\Scope',
                    'mapper' => 'Scope'
                ),
                'client_id' => array(
                    'type' => 'relation',
                    'name' => 'client',
                    'entity_field_name' => 'clientId',
                    'entity' => 'ZF\OAuth2\Doctrine\Entity\Client',
                    'datatype' => 'integer'
                ),
                'user_id' => array(
                    'type' => 'relation',
                    'name' => 'user',
                    'entity_field_name' => 'id',
                    'entity' => $userEntity,
                    'datatype' => 'integer',
                    'allow_null' => true
                )
            )
        ),
```
It i s not problem but when I copied configuration from module I thought it is possible to change.
Regarding indexes I will add them dynamically.

**Comment by TomHAnderson** [comment]
See http://blog.tomhanderson.com/2016/03/zf-oauth2-doctrine-with-bigint.html?q=bigint and adjust the instructions to modify the accessToken field
