### ISSUE TITLE
Error in RuntimeReflectionService.php

### ISSUE THREAD

**Issue by aburcheri** [API-Skeletons/zf-oauth2-doctrine#92]
when doing a ./vendor/bin/doctrine-module orm:schema-tool:update --force I get following error:
In RuntimeReflectionService.php line 80:
Property BMEntities\Entity\User::$client does not exist 

What is the cause of this error?

**Comment by TomHAnderson** [comment]
http://doctrine-in-apigility-docs.readthedocs.io/en/latest/zf-oauth2-doctrine/user%20entity%20configuration.html
