### ISSUE TITLE
Transition to  laminas-api-tools

### ISSUE THREAD

**Issue by mwalper** [API-Skeletons/zf-oauth2-doctrine#95]
Hi,
are there plans to transition this into Laminas Project? Since you already moved DoctrineModule it would be great to move this too.
It would also be great to see the following Repos to migrate too
 
zf-oauth2-doctrine-permissions-acl
zf-doctrine-hydrator
zf-doctrine-audit

**Comment by TomHAnderson** [comment]
You left zf-oauth2-doctrine-identity off the list.  I intend to merge zf-oauth2-doctrine-identity and zf-oauth2-doctrine.

I will be renaming the modules in support of api-tools and laminas.  I'm looking for clarification on how to do this here: https://discourse.laminas.dev/t/questions-on-the-naming-of-modules-for-laminas-mezzio-api-tools/1309

**Comment by TomHAnderson** [comment]
https://github.com/api-skeletons/oauth2-doctrine
